"""Build src/data/title_taxonomy.json.

Merges:
1. src/data/title_taxonomy_core.json — the 297 curated tech/business entries
2. An embedded ESCO/O*NET-style occupations catalog below, covering the role
   families the core misses (healthcare, trades, retail, legal, education,
   logistics, finance, operations, sales, creative, science).

Cubicals has no ESCO *occupations* export (only curated_skills.json), so the
catalog lives here. Families and aliases were chosen from the actual unmatched
title_raw values in the jobs table (19.7k unmatched at 297 entries).

Run: python -m scripts.build_title_taxonomy
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "src" / "data" / "title_taxonomy_core.json"
OUT = ROOT / "src" / "data" / "title_taxonomy.json"

# (canonical, function, aliases) — base aliases only; level/seniority variants
# are handled by token_set_ratio and the title cleaner, not by alias explosion.
CATALOG: list[tuple[str, str, list[str]]] = [
    # --- Healthcare: physicians & advanced practice ---
    ("Physician", "healthcare", ["doctor", "md", "medical doctor", "staff physician"]),
    ("Primary Care Physician", "healthcare", ["pcp", "primary care doctor", "per diem primary care physician"]),
    ("Family Medicine Physician", "healthcare", ["family physician", "family practice physician", "per diem family medicine physician"]),
    ("Internal Medicine Physician", "healthcare", ["internist", "internal medicine doctor"]),
    ("Emergency Medicine Physician", "healthcare", ["er physician", "emergency room physician", "ed physician"]),
    ("Urgent Care Physician", "healthcare", ["urgent care doctor"]),
    ("Pediatrician", "healthcare", ["pediatric physician", "pediatrics physician"]),
    ("Psychiatrist", "healthcare", ["psychiatry physician"]),
    ("Hospitalist", "healthcare", ["hospital medicine physician"]),
    ("Anesthesiologist", "healthcare", ["anesthesia physician"]),
    ("Radiologist", "healthcare", ["radiology physician"]),
    ("Dermatologist", "healthcare", ["dermatology physician"]),
    ("Cardiologist", "healthcare", ["cardiology physician"]),
    ("OB/GYN Physician", "healthcare", ["obgyn", "obstetrician gynecologist", "ob gyn"]),
    ("Surgeon", "healthcare", ["general surgeon", "surgery physician"]),
    ("Nurse Practitioner", "healthcare", ["np", "family nurse practitioner", "fnp", "aprn", "psychiatric nurse practitioner"]),
    ("Physician Assistant", "healthcare", ["pa", "pa-c", "physician associate"]),
    # --- Healthcare: nursing & allied ---
    ("Registered Nurse", "healthcare", ["rn", "staff nurse", "charge nurse", "er nurse", "icu nurse", "or nurse"]),
    ("Licensed Practical Nurse", "healthcare", ["lpn", "lvn", "licensed vocational nurse"]),
    ("Certified Nursing Assistant", "healthcare", ["cna", "nursing assistant", "nurse aide", "patient care assistant", "patient care technician"]),
    ("Nurse Manager", "healthcare", ["nursing manager", "director of nursing", "nursing supervisor"]),
    ("Medical Assistant", "healthcare", ["ma", "certified medical assistant", "clinical assistant"]),
    ("Phlebotomist", "healthcare", ["phlebotomy technician", "mobile phlebotomist"]),
    ("Pharmacist", "healthcare", ["staff pharmacist", "clinical pharmacist", "retail pharmacist"]),
    ("Pharmacy Technician", "healthcare", ["pharmacy tech", "certified pharmacy technician"]),
    ("Physical Therapist", "healthcare", ["pt", "physiotherapist"]),
    ("Physical Therapist Assistant", "healthcare", ["pta"]),
    ("Occupational Therapist", "healthcare", ["ot"]),
    ("Speech Language Pathologist", "healthcare", ["slp", "speech therapist"]),
    ("Respiratory Therapist", "healthcare", ["rt", "respiratory care practitioner"]),
    ("Radiologic Technologist", "healthcare", ["radiology technician", "x-ray technician", "x ray tech", "imaging technologist"]),
    ("Ultrasound Technologist", "healthcare", ["sonographer", "ultrasound technician"]),
    ("Surgical Technologist", "healthcare", ["surgical tech", "operating room technician", "scrub tech"]),
    ("Medical Laboratory Technician", "healthcare", ["lab technician", "medical lab tech", "laboratory technologist", "clinical laboratory scientist"]),
    ("Paramedic", "healthcare", ["emt", "emergency medical technician"]),
    ("Dentist", "healthcare", ["general dentist", "dds"]),
    ("Dental Hygienist", "healthcare", ["registered dental hygienist", "rdh"]),
    ("Dental Assistant", "healthcare", ["registered dental assistant"]),
    ("Optometrist", "healthcare", ["od"]),
    ("Veterinarian", "healthcare", ["dvm", "associate veterinarian"]),
    ("Veterinary Technician", "healthcare", ["vet tech", "veterinary assistant", "veterinary nurse"]),
    ("Therapist", "healthcare", ["licensed therapist", "mental health therapist", "lmft", "lcsw", "counselor", "mental health counselor"]),
    ("Psychologist", "healthcare", ["clinical psychologist", "licensed psychologist"]),
    ("Behavior Technician", "healthcare", ["rbt", "registered behavior technician", "aba therapist", "behavioral therapist"]),
    ("Social Worker", "healthcare", ["case worker", "clinical social worker", "msw"]),
    ("Case Manager", "healthcare", ["care manager", "care coordinator", "rn case manager"]),
    ("Home Health Aide", "healthcare", ["hha", "caregiver", "home care aide", "personal care aide", "direct support professional"]),
    ("Dietitian", "healthcare", ["registered dietitian", "nutritionist"]),
    ("Chiropractor", "healthcare", ["dc"]),
    ("Medical Receptionist", "healthcare", ["front desk medical receptionist", "patient service representative", "patient access representative"]),
    ("Medical Biller", "healthcare", ["medical billing specialist", "medical coder", "billing and coding specialist"]),
    ("Clinical Research Coordinator", "healthcare", ["clinical trial coordinator", "study coordinator"]),
    ("Clinical Research Associate", "healthcare", ["cra"]),
    ("Intervention Specialist", "healthcare", ["behavior intervention specialist", "early intervention specialist"]),
    ("Massage Therapist", "healthcare", ["licensed massage therapist", "lmt"]),
    # --- Automotive & skilled trades ---
    ("Automotive Technician", "trades", ["auto technician", "automotive mechanic", "auto mechanic", "car mechanic", "experienced automotive technician", "automotive service technician"]),
    ("Auto Body Repair Technician", "trades", ["auto body technician", "collision repair technician", "body shop technician", "automotive wheel repair technician"]),
    ("Brake and Tire Technician", "trades", ["tire technician", "brake technician", "brake and tire auto technician", "tire installer"]),
    ("Vehicle Detailer", "trades", ["car detailer", "automotive detailer", "auto detailer", "detailer", "lot attendant", "automotive detailer lot attendant", "car washer"]),
    ("Automotive Parts Associate", "trades", ["parts associate", "parts counter associate", "automotive parts specialist", "parts advisor"]),
    ("Service Advisor", "trades", ["automotive service advisor", "service writer", "service consultant"]),
    ("Diesel Mechanic", "trades", ["diesel technician", "fleet mechanic", "heavy equipment mechanic"]),
    ("Maintenance Technician", "trades", ["facilities maintenance technician", "building maintenance technician", "maintenance mechanic", "industrial maintenance technician"]),
    ("Electrician", "trades", ["journeyman electrician", "master electrician", "electrical technician", "apprentice electrician"]),
    ("Plumber", "trades", ["journeyman plumber", "plumbing technician", "apprentice plumber"]),
    ("HVAC Technician", "trades", ["hvac installer", "hvac service technician", "hvac mechanic"]),
    ("Welder", "trades", ["welder fabricator", "mig welder", "tig welder", "pipe welder"]),
    ("Carpenter", "trades", ["finish carpenter", "framing carpenter"]),
    ("Machinist", "trades", ["cnc machinist", "manual machinist", "tool and die maker"]),
    ("CNC Operator", "trades", ["cnc machine operator", "machine operator"]),
    ("Assembler", "trades", ["production assembler", "assembly technician", "assembly worker", "manufacturing associate"]),
    ("Production Operator", "trades", ["production associate", "production worker", "manufacturing operator", "plant operator"]),
    ("Fabricator", "trades", ["metal fabricator", "sheet metal worker"]),
    ("Painter", "trades", ["industrial painter", "automotive painter"]),
    ("Locksmith", "trades", []),
    ("Landscaper", "trades", ["groundskeeper", "landscape technician", "lawn technician", "grounds maintenance"]),
    ("Pest Control Technician", "trades", ["exterminator"]),
    ("Field Service Technician", "trades", ["field technician", "field service engineer", "service technician"]),
    ("Installation Technician", "trades", ["installer", "install technician", "cable technician", "solar installer"]),
    ("Equipment Operator", "trades", ["heavy equipment operator", "crane operator", "excavator operator"]),
    ("Construction Laborer", "trades", ["general laborer", "construction worker", "laborer", "skilled laborer"]),
    ("Construction Superintendent", "trades", ["site superintendent", "construction supervisor", "site supervisor"]),
    ("Foreman", "trades", ["construction foreman", "crew foreman", "crew lead"]),
    # --- Transportation & logistics ---
    ("Truck Driver", "logistics", ["cdl driver", "cdl a driver", "cdl a local truck driver", "class a driver", "otr driver", "local truck driver", "cdl b driver", "regional truck driver"]),
    ("Delivery Driver", "logistics", ["courier", "route driver", "customer service delivery driver", "parcel delivery driver", "van driver", "driver"]),
    ("Bus Driver", "logistics", ["school bus driver", "shuttle driver", "transit operator"]),
    ("Forklift Operator", "logistics", ["forklift driver", "material handler", "warehouse forklift operator"]),
    ("Warehouse Associate", "logistics", ["warehouse worker", "warehouse operative", "fulfillment associate", "picker packer", "order picker", "package handler", "warehouse team member"]),
    ("Warehouse Manager", "logistics", ["warehouse supervisor", "warehouse lead", "distribution center manager", "fulfillment manager"]),
    ("Dispatcher", "logistics", ["truck dispatcher", "fleet dispatcher", "transportation dispatcher"]),
    ("Logistics Coordinator", "logistics", ["logistics associate", "logistics specialist", "transportation coordinator", "freight coordinator"]),
    ("Logistics Manager", "logistics", ["transportation manager", "distribution manager", "fleet manager"]),
    ("Supply Chain Analyst", "logistics", ["supply chain specialist", "supply chain coordinator"]),
    ("Supply Chain Manager", "logistics", ["supply chain director", "head of supply chain"]),
    ("Procurement Specialist", "logistics", ["buyer", "purchasing agent", "purchasing specialist", "procurement analyst", "food and beverage buyer"]),
    ("Procurement Manager", "logistics", ["purchasing manager", "sourcing manager", "category manager"]),
    ("Inventory Specialist", "logistics", ["inventory control specialist", "inventory analyst", "inventory coordinator", "stock associate", "stocker"]),
    ("Shipping and Receiving Clerk", "logistics", ["shipping clerk", "receiving clerk", "shipping coordinator", "freight handler"]),
    # --- Retail, food & customer service ---
    ("Customer Service Representative", "retail", ["csr", "customer service rep", "customer service agent", "customer support representative", "customer service delivery advocate", "customer care representative", "overnight customer service representative", "call center representative", "contact center agent"]),
    ("Customer Support Specialist", "retail", ["customer support associate", "customer experience specialist", "customer care specialist", "support specialist", "technical support representative"]),
    ("Shift Supervisor", "retail", ["shift lead", "shift leader", "shift manager", "motor vehicle shift supervisor"]),
    ("Store Manager", "retail", ["retail store manager", "branch manager", "general manager retail"]),
    ("Assistant Store Manager", "retail", ["assistant manager", "motor vehicle assistant store manager", "assistant general manager"]),
    ("Retail Sales Associate", "retail", ["sales associate", "retail associate", "store associate", "sales floor associate", "retail team member"]),
    ("Cashier", "retail", ["front end cashier", "checkout associate"]),
    ("Merchandiser", "retail", ["retail merchandiser", "visual merchandiser", "merchandising associate"]),
    ("Barista", "retail", ["coffee barista", "cafe associate"]),
    ("Server", "retail", ["waiter", "waitress", "restaurant server", "food server", "banquet server"]),
    ("Bartender", "retail", ["mixologist"]),
    ("Host", "retail", ["hostess", "restaurant host", "front of house host"]),
    ("Cook", "retail", ["line cook", "prep cook", "grill cook", "kitchen cook", "fry cook"]),
    ("Chef", "retail", ["sous chef", "executive chef", "head chef", "chef de partie", "pastry chef"]),
    ("Kitchen Manager", "retail", ["back of house manager", "culinary manager"]),
    ("Restaurant Manager", "retail", ["food service manager", "restaurant general manager", "front of house manager"]),
    ("Dishwasher", "retail", ["kitchen steward", "utility worker"]),
    ("Housekeeper", "retail", ["room attendant", "housekeeping attendant", "hotel housekeeper", "cleaner"]),
    ("Custodian", "retail", ["janitor", "custodial worker", "janitorial associate", "porter"]),
    ("Hotel Front Desk Agent", "retail", ["front desk agent", "guest service agent", "front desk associate", "front desk receptionist"]),
    ("Security Guard", "retail", ["security officer", "security associate", "unarmed security officer", "armed security officer", "loss prevention officer", "loss prevention associate"]),
    # --- Legal ---
    ("Attorney", "legal", ["lawyer", "associate attorney", "staff attorney", "counsel", "of counsel"]),
    ("Litigation Attorney", "legal", ["litigation associate", "trial attorney", "litigator", "workers compensation attorney", "personal injury attorney", "insurance defense attorney"]),
    ("Corporate Attorney", "legal", ["corporate counsel", "in-house counsel", "transactional attorney", "commercial counsel"]),
    ("General Counsel", "legal", ["chief legal officer", "deputy general counsel", "associate general counsel", "assistant general counsel"]),
    ("Patent Attorney", "legal", ["ip attorney", "intellectual property attorney", "patent agent"]),
    ("Paralegal", "legal", ["litigation paralegal", "corporate paralegal", "senior paralegal", "personal injury paralegal", "presuit paralegal"]),
    ("Legal Assistant", "legal", ["legal secretary", "litigation assistant", "presuit secretary", "legal administrative assistant"]),
    ("Legal Engineer", "legal", ["legal technologist", "legal solutions engineer"]),
    ("Compliance Officer", "legal", ["compliance manager", "compliance specialist", "regulatory compliance officer", "compliance analyst"]),
    ("Contract Manager", "legal", ["contracts administrator", "contract specialist", "contracts manager"]),
    ("Claims Adjuster", "legal", ["claims examiner", "claims specialist", "claims representative", "claims analyst"]),
    # --- Education ---
    ("Teacher", "education", ["classroom teacher", "lead teacher", "elementary teacher", "elementary school teacher", "middle school teacher", "high school teacher"]),
    ("Substitute Teacher", "education", ["daily substitute teacher", "guest teacher", "supply teacher"]),
    ("Math Teacher", "education", ["mathematics teacher"]),
    ("Science Teacher", "education", ["biology teacher", "chemistry teacher", "physics teacher"]),
    ("English Teacher", "education", ["ela teacher", "language arts teacher", "english language arts teacher"]),
    ("Special Education Teacher", "education", ["sped teacher", "special ed teacher", "resource teacher"]),
    ("ESL Teacher", "education", ["esol teacher", "english as a second language teacher"]),
    ("Preschool Teacher", "education", ["early childhood teacher", "pre-k teacher", "infant teacher", "toddler teacher"]),
    ("Teaching Assistant", "education", ["teacher aide", "paraprofessional", "instructional aide", "classroom aide", "teacher assistant"]),
    ("Tutor", "education", ["academic tutor", "math tutor", "reading tutor", "online tutor"]),
    ("School Counselor", "education", ["guidance counselor", "academic counselor", "college counselor"]),
    ("School Principal", "education", ["assistant principal", "head of school", "vice principal"]),
    ("Professor", "education", ["assistant professor", "associate professor", "adjunct professor", "lecturer", "adjunct faculty", "instructor"]),
    ("Instructional Designer", "education", ["learning designer", "curriculum designer", "learning experience designer", "curriculum developer"]),
    ("Trainer", "education", ["corporate trainer", "training specialist", "learning and development specialist", "l&d specialist", "technical trainer"]),
    ("Childcare Provider", "education", ["childcare worker", "daycare teacher", "nanny", "child care assistant"]),
    ("Librarian", "education", ["library assistant", "media specialist"]),
    ("Athletic Coach", "education", ["coach", "head coach", "assistant coach", "fitness coach", "personal trainer"]),
    # --- Finance & accounting ---
    ("Accountant", "finance", ["staff accountant", "general ledger accountant", "gl accountant", "corporate accountant", "cpa", "fund accountant", "property accountant", "project accountant", "cost accountant"]),
    ("Accounting Manager", "finance", ["accounting supervisor", "assistant controller", "accounting lead"]),
    ("Controller", "finance", ["financial controller", "corporate controller", "plant controller"]),
    ("Chief Financial Officer", "finance", ["cfo", "vp of finance", "vice president of finance", "head of finance", "finance director", "director of finance"]),
    ("Bookkeeper", "finance", ["full charge bookkeeper", "accounting clerk", "accounts clerk"]),
    ("Accounts Payable Specialist", "finance", ["ap specialist", "accounts payable clerk", "ap clerk", "accounts payable coordinator"]),
    ("Accounts Receivable Specialist", "finance", ["ar specialist", "accounts receivable clerk", "ar clerk", "collections specialist", "billing specialist", "billing coordinator"]),
    ("Payroll Specialist", "finance", ["payroll administrator", "payroll coordinator", "payroll manager", "payroll analyst"]),
    ("Auditor", "finance", ["internal auditor", "external auditor", "audit associate", "audit manager", "it auditor", "staff auditor"]),
    ("Tax Accountant", "finance", ["tax associate", "tax analyst", "tax manager", "tax preparer", "tax senior"]),
    ("Financial Planning Analyst", "finance", ["fp&a analyst", "fp&a manager", "financial planning and analysis analyst", "corporate finance analyst"]),
    ("Financial Advisor", "finance", ["wealth advisor", "financial planner", "wealth manager", "financial consultant", "investment advisor"]),
    ("Investment Analyst", "finance", ["equity research analyst", "research analyst finance", "investment associate", "private equity analyst", "venture capital analyst"]),
    ("Portfolio Manager", "finance", ["asset manager", "investment manager", "fund manager"]),
    ("Investment Banking Analyst", "finance", ["investment banking associate", "ib analyst", "m&a analyst"]),
    ("Quantitative Researcher", "finance", ["quant researcher", "quantitative research analyst", "quantitative analyst", "quant analyst"]),
    ("Quantitative Developer", "finance", ["quant developer", "quantitative engineer", "quant dev"]),
    ("Trader", "finance", ["equity trader", "options trader", "fixed income trader", "execution trader", "quantitative trader"]),
    ("Actuary", "finance", ["actuarial analyst", "actuarial associate", "associate actuary"]),
    ("Underwriter", "finance", ["insurance underwriter", "mortgage underwriter", "commercial underwriter", "underwriting analyst"]),
    ("Loan Officer", "finance", ["mortgage loan officer", "loan originator", "commercial loan officer", "loan processor"]),
    ("Credit Analyst", "finance", ["credit risk analyst", "credit underwriter", "credit officer"]),
    ("Risk Analyst", "finance", ["risk manager", "market risk analyst", "operational risk analyst", "enterprise risk manager", "risk management analyst"]),
    ("Treasury Analyst", "finance", ["treasury manager", "cash management analyst", "treasurer"]),
    ("Bank Teller", "finance", ["teller", "personal banker", "universal banker", "relationship banker", "branch associate"]),
    ("Insurance Agent", "finance", ["insurance broker", "insurance producer", "licensed insurance agent", "insurance sales agent"]),
    ("Revenue Cycle Specialist", "finance", ["revenue cycle analyst", "revenue cycle manager", "revenue analyst", "revenue operations analyst"]),
    ("Fraud Analyst", "finance", ["fraud investigator", "fraud specialist", "aml analyst", "bsa analyst", "kyc analyst", "sanctions analyst"]),
    # --- Operations, admin & HR ---
    ("Administrative Assistant", "operations", ["admin assistant", "office assistant", "administrative coordinator", "administrative specialist", "clerical assistant"]),
    ("Executive Assistant", "operations", ["ea", "executive administrative assistant", "executive assistant to ceo", "personal assistant"]),
    ("Office Manager", "operations", ["office administrator", "office coordinator", "front office manager"]),
    ("Receptionist", "operations", ["front desk receptionist", "front office receptionist", "office receptionist"]),
    ("Data Entry Clerk", "operations", ["data entry specialist", "data entry operator", "data entry associate"]),
    ("Operations Associate", "operations", ["operations coordinator", "operations specialist", "business operations associate", "ops associate"]),
    ("Operations Analyst", "operations", ["business operations analyst", "ops analyst", "process analyst", "operations research analyst"]),
    ("Operations Manager", "operations", ["business operations manager", "ops manager", "general operations manager", "team lead market operations", "market operations lead"]),
    ("Director of Operations", "operations", ["vp of operations", "head of operations", "coo", "chief operating officer", "vice president of operations"]),
    ("Facilities Manager", "operations", ["facilities coordinator", "facility manager", "building manager"]),
    ("HSE Coordinator", "operations", ["health safety and environmental coordinator", "ehs coordinator", "hse manager", "ehs manager", "safety coordinator", "environmental health and safety specialist"]),
    ("Safety Manager", "operations", ["safety specialist", "site safety manager", "safety officer", "occupational health and safety specialist"]),
    ("Quality Assurance Specialist", "operations", ["quality specialist", "quality control inspector", "qc inspector", "quality technician", "quality control technician", "quality inspector"]),
    ("Quality Manager", "operations", ["quality assurance manager", "qa manager operations", "quality control manager", "director of quality"]),
    ("Human Resources Generalist", "operations", ["hr generalist", "human resources specialist", "hr specialist", "people operations generalist"]),
    ("Human Resources Coordinator", "operations", ["hr coordinator", "hr assistant", "people operations coordinator", "hr administrator"]),
    ("Human Resources Business Partner", "operations", ["hrbp", "hr business partner", "people business partner", "senior hrbp"]),
    ("Human Resources Director", "operations", ["hr director", "vp of people", "chief people officer", "vp of human resources", "head of people", "chro"]),
    ("Talent Acquisition Specialist", "operations", ["talent acquisition partner", "talent acquisition coordinator", "talent sourcer", "sourcing recruiter", "talent acquisition manager"]),
    ("Recruiting Coordinator", "operations", ["recruitment coordinator", "talent coordinator", "hiring coordinator"]),
    ("Compensation Analyst", "operations", ["benefits analyst", "compensation and benefits analyst", "total rewards analyst", "benefits administrator", "benefits specialist"]),
    ("Executive Recruiter", "operations", ["executive search consultant", "headhunter", "search consultant"]),
    ("Workplace Experience Coordinator", "operations", ["workplace coordinator", "workplace experience manager", "employee experience specialist"]),
    ("Property Manager", "operations", ["community manager property", "assistant property manager", "regional property manager", "leasing manager"]),
    ("Leasing Consultant", "operations", ["leasing agent", "leasing specialist", "leasing associate"]),
    ("Real Estate Agent", "operations", ["realtor", "real estate salesperson", "real estate associate", "real estate broker"]),
    ("Event Coordinator", "operations", ["event planner", "event specialist", "events manager", "event operations manager", "meeting planner"]),
    ("Translator", "operations", ["interpreter", "medical interpreter", "linguist"]),
    # --- Sales & marketing (beyond core) ---
    ("Sales Representative", "sales", ["sales rep", "outside sales representative", "inside sales representative", "field sales representative", "territory sales representative", "b2b sales representative"]),
    ("Sales Specialist", "sales", ["product sales specialist", "sales consultant", "lakebase sales specialist", "solutions specialist"]),
    ("Sales Manager", "sales", ["regional sales manager", "territory sales manager", "area sales manager", "district sales manager", "inside sales manager"]),
    ("Sales Director", "sales", ["director of sales", "vp of sales", "vice president of sales", "head of sales", "cro", "chief revenue officer", "director of strategic sales"]),
    ("Business Development Representative", "sales", ["bdr", "business development rep", "development representative", "hybrid development representative", "outbound sdr"]),
    ("Business Development Manager", "sales", ["bd manager", "business development director", "business development executive", "partnerships development manager"]),
    ("Enterprise Account Executive", "sales", ["enterprise ae", "strategic account executive", "majors account executive", "large enterprise account executive"]),
    ("Sales Operations Analyst", "sales", ["sales ops analyst", "revenue operations manager", "revops", "sales operations manager", "deal desk analyst"]),
    ("Sales Enablement Manager", "sales", ["enablement manager", "revenue enablement manager", "sales enablement specialist"]),
    ("Channel Manager", "sales", ["channel sales manager", "partner manager", "channel account manager", "alliances manager", "partner development manager"]),
    ("Retail Sales Manager", "sales", ["counter sales", "showroom sales", "floor sales manager"]),
    ("Solutions Consultant", "sales", ["presales consultant", "pre-sales engineer", "solution consultant", "value engineer", "presales solutions consultant"]),
    ("Customer Success Associate", "sales", ["customer success specialist", "customer success coordinator", "client success associate", "clinical success specialist"]),
    ("Brand Manager", "marketing", ["associate brand manager", "senior brand manager", "brand marketing manager", "brand strategist"]),
    ("Communications Manager", "marketing", ["corporate communications manager", "internal communications manager", "communications specialist", "pr manager", "public relations manager", "communications director"]),
    ("Social Media Manager", "marketing", ["social media specialist", "social media coordinator", "community manager", "social media strategist"]),
    ("SEO Specialist", "marketing", ["seo manager", "seo analyst", "search engine optimization specialist", "sem specialist", "sem manager"]),
    ("Digital Marketing Manager", "marketing", ["digital marketing specialist", "performance marketing manager", "paid media manager", "digital marketing coordinator", "ppc specialist"]),
    ("Email Marketing Manager", "marketing", ["lifecycle marketing manager", "crm marketing manager", "email marketing specialist", "retention marketing manager"]),
    ("Product Marketing Manager", "marketing", ["pmm", "senior product marketing manager", "director of product marketing", "product marketing lead"]),
    ("Field Marketing Manager", "marketing", ["events marketing manager", "regional marketing manager", "field marketing specialist"]),
    ("Marketing Coordinator", "marketing", ["marketing assistant", "marketing associate", "marketing specialist"]),
    ("Marketing Director", "marketing", ["vp of marketing", "head of marketing", "cmo", "chief marketing officer", "vice president of marketing"]),
    ("Copywriter", "marketing", ["content writer", "marketing copywriter", "creative copywriter", "senior copywriter"]),
    ("Brand Ambassador", "marketing", ["promotional representative", "product ambassador", "part time brand ambassador", "street team member"]),
    ("Market Research Analyst", "marketing", ["consumer insights analyst", "shopper insights manager", "insights analyst", "market intelligence analyst", "consumer insights manager"]),
    # --- Engineering (non-software) ---
    ("Civil Engineer", "engineering", ["civil design engineer", "site civil engineer", "civil project engineer"]),
    ("Structural Engineer", "engineering", ["structural design engineer"]),
    ("Mechanical Engineer", "engineering", ["mechanical design engineer", "hvac engineer", "product mechanical engineer"]),
    ("Electrical Engineer", "engineering", ["electrical design engineer", "power engineer", "power systems engineer", "controls electrical engineer"]),
    ("Industrial Engineer", "engineering", ["process improvement engineer", "manufacturing systems engineer"]),
    ("Manufacturing Engineer", "engineering", ["production engineer", "process engineer manufacturing"]),
    ("Process Engineer", "engineering", ["chemical process engineer", "process development engineer"]),
    ("Chemical Engineer", "engineering", ["process chemical engineer"]),
    ("Quality Engineer", "engineering", ["supplier quality engineer", "quality assurance engineer manufacturing", "sqe"]),
    ("Project Engineer", "engineering", ["construction project engineer", "field project engineer"]),
    ("Field Engineer", "engineering", ["field applications engineer", "fae", "site engineer"]),
    ("Controls Engineer", "engineering", ["automation engineer controls", "plc engineer", "instrumentation and controls engineer", "scada engineer"]),
    ("Aerospace Engineer", "engineering", ["aeronautical engineer", "flight systems engineer"]),
    ("Environmental Engineer", "engineering", ["environmental compliance engineer"]),
    ("Geotechnical Engineer", "engineering", ["geotech engineer"]),
    ("Hardware Engineer", "engineering", ["electrical hardware engineer", "hardware design engineer", "pcb design engineer", "asic engineer", "fpga engineer"]),
    ("Test Engineer (Hardware)", "engineering", ["hardware test engineer", "validation engineer", "verification engineer hardware"]),
    ("Construction Project Manager", "engineering", ["construction manager", "associate construction project manager", "construction pm", "preconstruction manager"]),
    ("Estimator", "engineering", ["construction estimator", "cost estimator", "senior estimator", "preconstruction estimator"]),
    ("Surveyor", "engineering", ["land surveyor", "survey technician", "survey crew chief"]),
    ("CAD Designer", "engineering", ["cad technician", "cad drafter", "drafter", "autocad drafter", "revit designer", "bim modeler"]),
    ("Architect (Building)", "engineering", ["licensed architect", "project architect", "architectural designer", "design architect"]),
    # --- Tech roles missing from core ---
    ("Forward Deployed Engineer", "engineering", ["fde", "deployed engineer", "forward deployed software engineer", "sr. forward deployed engineer"]),
    ("Deployment Strategist", "engineering", ["forward deployed strategist", "implementation strategist"]),
    ("Solution Engineer", "engineering", ["solutions engineer presales", "customer solutions engineer", "partner solutions engineer"]),
    ("Linux Engineer", "engineering", ["linux systems engineer", "linux administrator", "unix engineer", "unix administrator"]),
    ("Systems Administrator", "engineering", ["sysadmin", "system administrator", "windows administrator", "windows systems administrator", "it systems administrator"]),
    ("IT Support Specialist", "engineering", ["help desk technician", "helpdesk analyst", "it technician", "desktop support technician", "it support analyst", "service desk analyst", "technical support specialist", "it help desk"]),
    ("IT Manager", "engineering", ["it director", "director of it", "information technology manager", "it operations manager", "vp of it"]),
    ("Database Administrator", "engineering", ["dba", "sql server dba", "oracle dba", "postgres dba", "database engineer"]),
    ("Salesforce Developer", "engineering", ["salesforce engineer", "salesforce administrator", "salesforce admin", "salesforce consultant", "salesforce architect"]),
    ("SAP Consultant", "engineering", ["sap analyst", "sap developer", "sap basis administrator", "sap functional consultant", "erp consultant", "erp analyst"]),
    ("Workday Analyst", "engineering", ["workday consultant", "workday administrator", "hris analyst", "hris administrator", "hris manager"]),
    ("ServiceNow Developer", "engineering", ["servicenow administrator", "servicenow engineer", "servicenow architect"]),
    ("Business Intelligence Developer", "data", ["bi developer", "bi engineer", "power bi developer", "tableau developer", "looker developer"]),
    ("Data Governance Analyst", "data", ["data steward", "data quality analyst", "master data analyst", "data governance manager", "mdm analyst"]),
    ("GIS Analyst", "data", ["gis specialist", "gis technician", "gis developer", "geospatial analyst"]),
    ("Technical Program Manager", "management", ["tpm", "technical program lead", "senior technical program manager", "principal technical program manager"]),
    ("Delivery Manager", "management", ["engagement manager", "client delivery manager", "service delivery manager", "agile delivery manager"]),
    ("Chief of Staff", "management", ["chief of staff to ceo", "business chief of staff"]),
    ("Founder's Office Associate", "management", ["founders office", "ceo office associate", "strategy and operations associate"]),
    ("Strategy Consultant", "management", ["management consultant", "strategy associate", "consultant", "senior consultant", "principal consultant", "associate consultant"]),
    ("Strategy and Operations Manager", "management", ["strategy and ops manager", "business strategy manager", "corporate strategy manager", "strategy manager"]),
    ("Product Operations Manager", "product", ["product ops manager", "product operations and strategy manager", "product operations analyst"]),
    ("Product Lead", "product", ["lead product manager", "group product manager", "gpm", "head of product", "principal product manager"]),
    ("Program Coordinator", "operations", ["program associate", "program specialist", "program administrator"]),
    ("Grants Manager", "operations", ["grant writer", "grants administrator", "development coordinator nonprofit"]),
    # --- Science & research ---
    ("Research Scientist (Life Sciences)", "science", ["research associate", "senior research associate", "lab scientist", "bench scientist", "r&d scientist"]),
    ("Biologist", "science", ["molecular biologist", "microbiologist", "cell biologist", "wildlife biologist"]),
    ("Chemist", "science", ["analytical chemist", "organic chemist", "formulation chemist", "qc chemist"]),
    ("Biostatistician", "science", ["statistical programmer", "sas programmer", "senior biostatistician"]),
    ("Epidemiologist", "science", ["public health analyst", "public health epidemiologist"]),
    ("Materials Scientist", "science", ["materials engineer", "polymer scientist", "metallurgist"]),
    ("Lab Technician (Science)", "science", ["laboratory assistant", "research technician", "lab assistant", "r&d technician"]),
    ("Environmental Scientist", "science", ["environmental specialist", "environmental analyst", "environmental consultant", "ecologist"]),
    ("Food Scientist", "science", ["food technologist", "r&d food scientist", "flavor scientist"]),
    ("Geologist", "science", ["geoscientist", "hydrogeologist", "field geologist"]),
    # --- Creative & media ---
    ("Graphic Designer", "creative", ["visual designer print", "senior graphic designer", "junior graphic designer", "graphic artist", "production designer"]),
    ("Video Editor", "creative", ["video producer", "post production editor", "multimedia editor", "videographer"]),
    ("Photographer", "creative", ["staff photographer", "product photographer", "studio photographer"]),
    ("Animator", "creative", ["motion designer", "motion graphics designer", "2d animator", "3d animator"]),
    ("3D Artist", "creative", ["3d modeler", "character artist", "environment artist", "texture artist"]),
    ("Game Designer", "creative", ["level designer", "gameplay designer", "systems designer games"]),
    ("Game Producer", "creative", ["producer games", "associate producer", "executive producer"]),
    ("Art Director", "creative", ["associate art director", "senior art director", "creative lead"]),
    ("Creative Director", "creative", ["executive creative director", "group creative director", "head of creative"]),
    ("Content Creator", "creative", ["content producer", "digital content creator", "multimedia content producer", "content specialist"]),
    ("Journalist", "creative", ["reporter", "staff writer", "news reporter", "correspondent"]),
    ("Editor", "creative", ["managing editor", "copy editor", "senior editor", "editorial manager", "content editor"]),
    ("Audio Engineer", "creative", ["sound engineer", "sound designer", "audio technician", "mixing engineer"]),
    ("Music Teacher", "education", ["piano teacher", "guitar teacher", "voice teacher", "music instructor"]),
    ("UX Writer", "creative", ["content strategist", "ux content designer", "product content strategist"]),
    # --- Public service & misc ---
    ("Police Officer", "public_service", ["law enforcement officer", "patrol officer", "deputy sheriff"]),
    ("Firefighter", "public_service", ["firefighter emt", "fire captain"]),
    ("Correctional Officer", "public_service", ["detention officer", "corrections officer"]),
    ("Probation Officer", "public_service", ["parole officer", "community supervision officer"]),
    ("Emergency Dispatcher", "public_service", ["911 dispatcher", "public safety dispatcher", "emergency communications operator"]),
    ("Flight Attendant", "public_service", ["cabin crew", "inflight crew member"]),
    ("Pilot", "public_service", ["airline pilot", "first officer", "commercial pilot", "captain pilot"]),
    ("Aircraft Mechanic", "trades", ["a&p mechanic", "aircraft maintenance technician", "avionics technician"]),
    ("Postal Worker", "public_service", ["mail carrier", "mail handler", "postal clerk"]),
    ("Funeral Director", "public_service", ["mortician", "embalmer"]),
    ("Clergy", "public_service", ["pastor", "chaplain", "minister"]),
    ("Urban Planner", "public_service", ["city planner", "planning analyst", "community planner"]),
    ("Policy Analyst", "public_service", ["public policy analyst", "government affairs analyst", "legislative analyst", "policy associate"]),
    ("Government Affairs Manager", "public_service", ["public affairs manager", "government relations manager", "lobbyist"]),
]

CATALOG += [
    # --- High-frequency aliases observed in unmatched title_raw values ---
    ("Software Engineer", "engineering", ["member of technical staff", "mts", "principal member of technical staff"]),
    ("Auto Body Repair Technician", "trades", ["auto body prepper", "paintless dent repair technician", "automotive cosmetic inspector"]),
    ("Pipeline Technician", "trades", ["gas distribution technician"]),
    ("Sales Specialist", "sales", ["specialist seller"]),
    ("Trader", "finance", ["trading specialist"]),
    ("Operations Manager", "operations", ["bizops manager", "business operations lead"]),
    ("Warehouse Associate", "logistics", ["fulfillment team member", "freight receiving associate"]),
    ("Transaction Coordinator", "operations", ["real estate transaction coordinator", "escrow transaction coordinator"]),
    ("Manager Trainee", "retail", ["manager in training", "assistant manager trainee", "management trainee"]),
    ("Food Runner", "retail", ["runner", "busser", "busboy"]),
    ("Client Partner", "sales", ["regional client partner", "senior client partner", "principal client partner"]),
    ("Renewals Specialist", "sales", ["renewal specialist", "renewals manager", "renewals account manager"]),
    # --- Hospitality & travel ---
    ("Hotel Manager", "retail", ["hotel general manager", "hospitality manager", "lodging manager", "resort manager"]),
    ("Concierge", "retail", ["hotel concierge", "residential concierge", "lifestyle concierge"]),
    ("Valet Attendant", "retail", ["valet driver", "valet parking attendant", "parking attendant"]),
    ("Bellhop", "retail", ["bell attendant", "bellman", "luggage attendant"]),
    ("Reservation Agent", "retail", ["reservations coordinator", "booking agent", "travel coordinator"]),
    ("Travel Agent", "retail", ["travel consultant", "travel advisor", "corporate travel consultant"]),
    ("Tour Guide", "retail", ["tour operator", "excursion guide", "museum guide"]),
    ("Event Server", "retail", ["catering server", "banquet captain", "catering attendant"]),
    ("Casino Dealer", "retail", ["table games dealer", "poker dealer"]),
    ("Spa Manager", "retail", ["salon manager", "spa coordinator", "spa director"]),
    ("Hair Stylist", "retail", ["hairdresser", "cosmetologist", "barber", "salon stylist"]),
    ("Nail Technician", "retail", ["manicurist", "nail artist"]),
    ("Esthetician", "retail", ["skincare specialist", "facialist", "licensed esthetician"]),
    ("Fitness Instructor", "retail", ["group fitness instructor", "yoga instructor", "pilates instructor", "cycling instructor", "gym instructor"]),
    ("Lifeguard", "retail", ["pool lifeguard", "aquatics attendant", "swim instructor"]),
    ("Butcher", "retail", ["meat cutter", "meat clerk", "butcher block associate"]),
    ("Baker", "retail", ["pastry baker", "bakery associate", "bread baker", "cake decorator"]),
    ("Grocery Clerk", "retail", ["grocery associate", "produce clerk", "deli clerk", "dairy clerk", "grocery stocker"]),
    ("Pharmacy Cashier", "retail", ["pharmacy clerk", "drug store associate"]),
    ("Floral Designer", "retail", ["florist", "flower shop associate"]),
    ("Optician", "retail", ["optical technician", "eyewear consultant", "optical associate"]),
    ("Jeweler", "retail", ["jewelry consultant", "bench jeweler", "jewelry sales associate"]),
    ("Print Shop Associate", "retail", ["print production associate", "print technician", "copy center associate"]),
    ("Dry Cleaner", "retail", ["laundry attendant", "laundry associate", "presser"]),
    ("Tailor", "retail", ["seamstress", "alterations specialist", "sewing machine operator"]),
    # --- Energy, utilities & field ---
    ("Wind Turbine Technician", "trades", ["wind technician", "turbine technician"]),
    ("Solar Technician", "trades", ["solar panel installer", "pv installer", "solar field technician"]),
    ("Lineworker", "trades", ["lineman", "electrical lineworker", "powerline technician", "utility lineworker"]),
    ("Utility Technician", "trades", ["utility worker", "meter technician", "meter reader", "utility locator"]),
    ("Oil Field Worker", "trades", ["roustabout", "roughneck", "derrickhand", "floorhand"]),
    ("Pipeline Technician", "trades", ["pipeline operator", "pipefitter", "gas technician"]),
    ("Power Plant Operator", "trades", ["plant operator power", "control room operator", "boiler operator", "stationary engineer"]),
    ("Water Treatment Operator", "trades", ["wastewater operator", "water plant operator", "wastewater treatment technician"]),
    ("Elevator Mechanic", "trades", ["elevator technician", "elevator installer"]),
    ("Fire Sprinkler Technician", "trades", ["fire alarm technician", "fire protection technician", "sprinkler fitter"]),
    ("Appliance Repair Technician", "trades", ["appliance technician", "appliance service technician"]),
    ("Small Engine Mechanic", "trades", ["motorcycle mechanic", "marine mechanic", "powersports technician"]),
    ("Glazier", "trades", ["glass installer", "auto glass technician", "window installer"]),
    ("Roofer", "trades", ["roofing technician", "roofing installer", "commercial roofer"]),
    ("Flooring Installer", "trades", ["carpet installer", "tile setter", "hardwood floor installer"]),
    ("Drywall Installer", "trades", ["drywall finisher", "taper", "plasterer"]),
    ("Insulation Installer", "trades", ["insulator", "weatherization technician"]),
    ("Concrete Finisher", "trades", ["cement mason", "concrete laborer", "concrete worker"]),
    ("Ironworker", "trades", ["structural ironworker", "rebar worker", "steel erector"]),
    ("Rigger", "trades", ["rigging specialist", "crane rigger"]),
    ("Millwright", "trades", ["industrial millwright", "maintenance millwright"]),
    ("Heavy Equipment Technician", "trades", ["construction equipment mechanic", "equipment service technician"]),
    ("Auto Glass Installer", "trades", ["windshield technician", "auto glass repair technician"]),
    ("Sign Installer", "trades", ["sign technician", "sign maker", "sign fabricator"]),
    ("Mover", "logistics", ["moving crew member", "furniture mover", "relocation specialist"]),
    ("Sanitation Worker", "trades", ["garbage collector", "refuse collector", "waste management driver", "recycling worker"]),
    ("Tree Trimmer", "trades", ["arborist", "tree climber", "tree care specialist"]),
    ("Pool Technician", "trades", ["pool service technician", "pool cleaner", "pool maintenance"]),
    # --- More healthcare ---
    ("Athletic Trainer", "healthcare", ["certified athletic trainer", "sports medicine trainer"]),
    ("Recreation Therapist", "healthcare", ["recreational therapist", "activities director", "activities coordinator", "life enrichment coordinator"]),
    ("Music Therapist", "healthcare", ["board certified music therapist"]),
    ("Art Therapist", "healthcare", ["licensed art therapist"]),
    ("Genetic Counselor", "healthcare", ["genetics counselor"]),
    ("Audiologist", "healthcare", ["hearing specialist", "hearing aid specialist"]),
    ("Orthodontist", "healthcare", ["orthodontics dentist"]),
    ("Oral Surgeon", "healthcare", ["oral and maxillofacial surgeon"]),
    ("Endodontist", "healthcare", []),
    ("Periodontist", "healthcare", []),
    ("Podiatrist", "healthcare", ["foot and ankle specialist", "dpm"]),
    ("Midwife", "healthcare", ["certified nurse midwife", "cnm"]),
    ("Doula", "healthcare", ["birth doula", "postpartum doula"]),
    ("Lactation Consultant", "healthcare", ["ibclc", "lactation specialist"]),
    ("Sterile Processing Technician", "healthcare", ["sterilization technician", "spd technician", "central sterile technician"]),
    ("Dialysis Technician", "healthcare", ["hemodialysis technician", "patient care technician dialysis"]),
    ("EKG Technician", "healthcare", ["ecg technician", "cardiac monitor technician", "telemetry technician"]),
    ("Cath Lab Technologist", "healthcare", ["cardiovascular technologist", "cardiac cath tech"]),
    ("MRI Technologist", "healthcare", ["mri tech", "magnetic resonance technologist"]),
    ("CT Technologist", "healthcare", ["ct tech", "computed tomography technologist"]),
    ("Mammography Technologist", "healthcare", ["mammographer"]),
    ("Nuclear Medicine Technologist", "healthcare", ["nuc med tech"]),
    ("Anesthesia Technician", "healthcare", ["anesthesia tech"]),
    ("Orthopedic Technician", "healthcare", ["cast technician", "orthopaedic technologist"]),
    ("Optometric Technician", "healthcare", ["ophthalmic technician", "ophthalmic assistant", "optometric assistant"]),
    ("Health Information Technician", "healthcare", ["health information specialist", "medical records clerk", "medical records specialist", "him technician"]),
    ("Utilization Review Nurse", "healthcare", ["utilization management nurse", "ur nurse", "prior authorization nurse"]),
    ("Infection Preventionist", "healthcare", ["infection control nurse", "infection control practitioner"]),
    ("Wound Care Nurse", "healthcare", ["wound ostomy nurse", "wocn"]),
    ("School Nurse", "healthcare", ["campus nurse"]),
    ("Occupational Health Nurse", "healthcare", ["employee health nurse", "workplace health nurse"]),
    ("Clinical Nurse Educator", "healthcare", ["nurse educator", "clinical educator", "nursing instructor"]),
    ("Medical Director", "healthcare", ["associate medical director", "regional medical director", "chief medical officer", "cmo medical"]),
    ("Clinical Director", "healthcare", ["director of clinical services", "clinical services manager", "director of clinical operations"]),
    ("Practice Manager", "healthcare", ["medical practice manager", "clinic manager", "medical office manager", "dental office manager"]),
    ("Hospital Administrator", "healthcare", ["healthcare administrator", "health services administrator"]),
    ("Patient Navigator", "healthcare", ["patient advocate", "patient liaison", "health navigator"]),
    ("Community Health Worker", "healthcare", ["outreach worker", "health educator", "community outreach specialist"]),
    ("Emergency Room Technician", "healthcare", ["er technician", "ed tech", "emergency department technician"]),
    ("Mental Health Technician", "healthcare", ["psychiatric technician", "behavioral health technician", "mental health associate", "psych tech"]),
    ("Substance Abuse Counselor", "healthcare", ["addiction counselor", "recovery specialist", "cadc", "substance use disorder counselor", "peer recovery specialist"]),
    ("Optical Lab Technician", "healthcare", ["lens technician", "optical laboratory technician"]),
    ("Veterinary Receptionist", "healthcare", ["veterinary client service representative", "vet front desk"]),
    ("Kennel Technician", "healthcare", ["kennel attendant", "animal care technician", "animal caretaker", "pet care specialist"]),
    ("Groomer", "retail", ["pet groomer", "dog groomer", "bather brusher"]),
    ("Dog Trainer", "retail", ["pet trainer", "canine trainer"]),
    # --- Banking, insurance & fintech ops ---
    ("Branch Manager (Banking)", "finance", ["bank branch manager", "banking center manager", "assistant branch manager"]),
    ("Mortgage Processor", "finance", ["loan processor mortgage", "mortgage loan processor", "loan closer", "mortgage closer"]),
    ("Escrow Officer", "finance", ["title officer", "escrow assistant", "title examiner", "settlement officer"]),
    ("Financial Analyst (Corporate)", "finance", ["senior financial analyst", "finance analyst", "business finance analyst"]),
    ("Billing Analyst", "finance", ["invoicing specialist", "billing analyst revenue"]),
    ("Grants Accountant", "finance", ["fund accountant nonprofit", "grants financial analyst"]),
    ("Payroll Tax Analyst", "finance", ["payroll tax specialist", "employment tax analyst"]),
    ("Pricing Analyst", "finance", ["pricing manager", "pricing strategist", "pricing specialist"]),
    ("Procurement Analyst", "finance", ["sourcing analyst", "spend analyst", "purchasing analyst"]),
    ("Investor Relations Manager", "finance", ["investor relations analyst", "ir manager", "shareholder relations"]),
    ("Corporate Development Manager", "finance", ["corp dev associate", "m&a associate", "corporate development analyst"]),
    ("Equity Administration Specialist", "finance", ["stock plan administrator", "equity compensation analyst"]),
    ("Insurance Claims Processor", "finance", ["claims processor", "claims clerk", "claims coordinator"]),
    ("Insurance Account Manager", "finance", ["commercial lines account manager", "personal lines account manager", "insurance csr"]),
    ("Actuarial Manager", "finance", ["actuarial director", "pricing actuary", "reserving actuary"]),
    ("Billing Manager", "finance", ["revenue cycle director", "patient financial services manager"]),
    ("Collections Agent", "finance", ["debt collector", "collections representative", "recovery specialist collections"]),
    # --- Government, nonprofit & misc professional ---
    ("Program Manager (Nonprofit)", "public_service", ["nonprofit program manager", "program director nonprofit"]),
    ("Volunteer Coordinator", "public_service", ["volunteer manager", "volunteer services coordinator"]),
    ("Fundraising Manager", "public_service", ["development manager nonprofit", "development director", "major gifts officer", "annual giving manager", "advancement officer"]),
    ("Community Organizer", "public_service", ["field organizer", "advocacy coordinator", "campaign organizer"]),
    ("City Administrator", "public_service", ["city manager", "town manager", "county administrator"]),
    ("Code Enforcement Officer", "public_service", ["building inspector", "code compliance officer", "housing inspector"]),
    ("Permit Technician", "public_service", ["permit coordinator", "permit specialist", "plans examiner"]),
    ("Court Clerk", "public_service", ["deputy court clerk", "judicial assistant", "court administrator"]),
    ("Court Reporter", "public_service", ["stenographer", "digital court reporter"]),
    ("Park Ranger", "public_service", ["forest ranger", "conservation officer"]),
    ("Recreation Coordinator", "public_service", ["parks and recreation coordinator", "recreation leader", "recreation supervisor"]),
    ("Immigration Officer", "public_service", ["immigration services officer", "asylum officer"]),
    ("Customs Broker", "logistics", ["customs entry writer", "customs compliance specialist", "trade compliance analyst", "import export coordinator"]),
    ("Air Traffic Controller", "public_service", ["atc specialist"]),
    ("Transit Planner", "public_service", ["transportation planner", "mobility planner"]),
    ("Archivist", "public_service", ["records manager", "records analyst", "records clerk"]),
    ("Museum Curator", "public_service", ["curator", "collections manager museum", "exhibitions manager"]),
    # --- Additional software/tech depth ---
    ("Web Developer", "engineering", ["website developer", "wordpress developer", "webmaster", "web programmer", "shopify developer"]),
    ("Software Architect", "engineering", ["application architect", "software solutions architect", "principal architect", "chief architect"]),
    ("Enterprise Architect", "engineering", ["domain architect", "business architect", "it architect"]),
    ("Data Architect", "data", ["data solutions architect", "data warehouse architect", "analytics architect"]),
    ("Integration Developer", "engineering", ["mulesoft developer", "boomi developer", "api integration developer", "middleware developer", "edi developer", "edi analyst"]),
    ("RPA Developer", "engineering", ["automation developer", "uipath developer", "rpa engineer", "process automation developer"]),
    ("Low-Code Developer", "engineering", ["power platform developer", "powerapps developer", "appian developer", "outsystems developer"]),
    ("Mainframe Developer", "engineering", ["cobol developer", "mainframe engineer", "as400 developer", "rpg developer"]),
    (".NET Developer", "engineering", ["c# developer", "dotnet developer", ".net engineer", "c# engineer"]),
    ("Java Developer", "engineering", ["java engineer", "java software engineer", "j2ee developer", "spring developer"]),
    ("Python Developer", "engineering", ["python engineer", "django developer", "python software engineer"]),
    ("PHP Developer", "engineering", ["laravel developer", "php engineer", "drupal developer", "magento developer"]),
    ("Ruby Developer", "engineering", ["ruby on rails developer", "rails engineer", "ruby engineer"]),
    ("Node.js Developer", "engineering", ["node developer", "nodejs engineer", "node engineer"]),
    ("React Developer", "engineering", ["react engineer", "react native developer", "reactjs developer"]),
    ("Golang Developer", "engineering", ["go developer", "go engineer", "golang engineer"]),
    ("Scala Developer", "engineering", ["scala engineer"]),
    ("C++ Developer", "engineering", ["c++ engineer", "c++ software engineer", "c/c++ developer"]),
    ("Rust Developer", "engineering", ["rust engineer", "rust software engineer"]),
    ("Kotlin Developer", "engineering", ["kotlin engineer"]),
    ("Flutter Developer", "engineering", ["flutter engineer", "dart developer"]),
    ("Technical Consultant", "engineering", ["it consultant", "technology consultant", "software consultant", "digital consultant"]),
    ("Implementation Consultant", "engineering", ["implementation specialist", "onboarding consultant", "deployment consultant", "professional services consultant"]),
    ("Technical Account Executive", "sales", ["technical sales representative", "technical sales specialist"]),
    ("Escalation Engineer", "engineering", ["escalation manager", "critical situation manager", "premier support engineer"]),
    ("Site Reliability Manager", "management", ["sre manager", "infrastructure manager", "platform engineering manager", "devops manager", "cloud operations manager"]),
    ("NOC Technician", "engineering", ["noc engineer", "noc analyst", "network operations technician"]),
    ("Telecommunications Technician", "engineering", ["telecom technician", "telecom engineer", "voip engineer", "fiber technician", "fiber splicer"]),
    ("Wireless Engineer", "engineering", ["rf engineer", "radio frequency engineer", "5g engineer", "cellular engineer"]),
    ("Broadcast Engineer", "engineering", ["av engineer", "audio visual technician", "av technician", "broadcast technician"]),
    ("Scrum Master (Senior)", "management", ["agile coach", "agile delivery lead", "rte", "release train engineer", "agile program manager"]),
    ("Product Owner", "product", ["technical product owner", "digital product owner", "platform product owner"]),
    ("Business Systems Analyst", "data", ["it business analyst", "systems analyst", "erp business analyst", "technical business analyst", "business system analyst"]),
    ("Configuration Analyst", "engineering", ["configuration manager", "configuration specialist"]),
    ("Release Manager", "engineering", ["release coordinator", "change manager it", "deployment manager"]),
]

# Specialty expansions — generate "<specialty> <base>" canonicals programmatically
_TEACHER_SUBJECTS = [
    "Social Studies", "History", "Spanish", "French", "Art", "Physical Education",
    "Computer Science", "Kindergarten", "Reading", "Drama", "Health",
]
_PHYSICIAN_SPECIALTIES = [
    "Neurology", "Oncology", "Orthopedic", "Urology", "Gastroenterology",
    "Pulmonology", "Nephrology", "Endocrinology", "Rheumatology", "Geriatric",
    "Occupational Medicine", "Pain Management", "Physical Medicine",
    "Sports Medicine", "Palliative Care",
]
_NURSE_SPECIALTIES = [
    "ICU", "Emergency Room", "Operating Room", "Labor and Delivery", "Pediatric",
    "Oncology", "Dialysis", "Home Health", "Hospice", "Psychiatric",
    "Telemetry", "Med Surg", "NICU", "PACU", "Cath Lab", "Travel",
    "Infusion", "Rehab",
]
_ATTORNEY_PRACTICES = [
    "Family Law", "Immigration", "Real Estate", "Employment", "Tax",
    "Bankruptcy", "Criminal Defense", "Estate Planning", "Healthcare",
    "Construction", "Environmental",
]
_MANAGER_DOMAINS = [
    # "<domain> Manager" roles common in US postings, not already covered
    ("Category", "operations"), ("Compliance", "legal"), ("Credit", "finance"),
    ("Customer Experience", "sales"), ("Demand Planning", "logistics"),
    ("District", "retail"), ("E-commerce", "marketing"), ("Environmental", "operations"),
    ("Field Operations", "operations"), ("Fleet Operations", "logistics"),
    ("Franchise", "operations"), ("Front Office", "retail"), ("Inside Sales", "sales"),
    ("Inventory", "logistics"), ("Loss Prevention", "retail"), ("Maintenance", "trades"),
    ("Manufacturing", "operations"), ("Merchandising", "retail"), ("Onboarding", "operations"),
    ("Patient Services", "healthcare"), ("Plant", "operations"), ("Production", "operations"),
    ("Regional Operations", "operations"), ("Retention", "marketing"), ("Route", "logistics"),
    ("Service", "operations"), ("Shift Operations", "operations"), ("Terminal", "logistics"),
    ("Territory", "sales"), ("Training", "education"), ("Vendor", "operations"),
]
_RECRUITER_DOMAINS = ["Healthcare", "Sales", "Executive Search", "Campus", "Staffing", "Corporate"]
_AE_VERTICALS = [
    "Healthcare", "Public Sector", "Financial Services", "Retail",
    "Manufacturing", "Startup", "SMB", "Commercial",
]
_ENGINEER_SPECIALTIES = [
    # software specialties beyond core
    ("Blockchain Engineer", ["web3 engineer", "smart contract engineer", "solidity engineer", "crypto engineer"]),
    ("Robotics Engineer", ["robotics software engineer", "autonomy engineer", "motion planning engineer"]),
    ("Simulation Engineer", ["simulation software engineer", "modeling and simulation engineer"]),
    ("Compiler Engineer", ["language tools engineer", "compiler developer"]),
    ("Graphics Engineer", ["rendering engineer", "gpu engineer", "shader engineer"]),
    ("Game Engineer", ["game developer", "gameplay engineer", "unity developer", "unreal engineer", "game programmer"]),
    ("Firmware Engineer", ["embedded firmware engineer", "firmware developer"]),
    ("Audio Software Engineer", ["dsp engineer", "audio dsp engineer"]),
    ("Search Engineer", ["search relevance engineer", "information retrieval engineer"]),
    ("Ads Engineer", ["ad tech engineer", "advertising engineer"]),
    ("Payments Engineer", ["fintech engineer", "payment systems engineer"]),
    ("Growth Engineer", ["growth software engineer", "experimentation engineer"]),
    ("Developer Productivity Engineer", ["developer experience engineer", "devex engineer", "engineering productivity engineer", "tools engineer"]),
    ("Observability Engineer", ["monitoring engineer", "telemetry engineer"]),
    ("Performance Engineer", ["performance software engineer", "capacity engineer"]),
    ("Localization Engineer", ["internationalization engineer", "i18n engineer"]),
    ("Hardware Security Engineer", ["silicon security engineer"]),
    ("Detection Engineer", ["detection and response engineer", "threat detection engineer"]),
    ("Incident Response Analyst", ["incident responder", "dfir analyst", "csirt analyst"]),
    ("Threat Intelligence Analyst", ["cyber threat intelligence analyst", "cti analyst"]),
    ("GRC Analyst", ["governance risk and compliance analyst", "security compliance analyst", "security grc manager"]),
    ("Identity Engineer", ["iam engineer", "identity and access management engineer", "identity architect"]),
    ("Cryptography Engineer", ["applied cryptographer", "cryptographer"]),
    ("Privacy Engineer", ["data privacy engineer", "privacy analyst"]),
    ("AI Safety Researcher", ["alignment researcher", "ai alignment engineer", "responsible ai engineer"]),
    ("Prompt Engineer", ["ai prompt engineer", "llm engineer", "genai engineer", "generative ai engineer"]),
    ("MLOps Engineer", ["ml infrastructure engineer", "ml ops engineer", "ml platform developer"]),
    ("Data Annotation Specialist", ["data labeling specialist", "annotation analyst", "ai data trainer"]),
]


def build() -> list[dict]:
    core = json.loads(CORE.read_text(encoding="utf-8"))
    entries: dict[str, dict] = {e["canonical"].lower(): e for e in core}

    def add(canonical: str, function: str, aliases: list[str]) -> None:
        key = canonical.lower()
        if key in entries:
            existing = entries[key]
            existing["function"] = function  # catalog functions are finer than core's
            have = {a.lower() for a in existing["aliases"]} | {key}
            existing["aliases"].extend(a for a in aliases if a.lower() not in have)
            return
        entries[key] = {
            "canonical": canonical,
            "function": function,
            "aliases": [a for a in aliases if a.lower() != key],
        }

    for canonical, function, aliases in CATALOG:
        add(canonical, function, aliases)

    for subject in _TEACHER_SUBJECTS:
        add(f"{subject} Teacher", "education", [f"{subject.lower()} instructor"])
    for spec in _PHYSICIAN_SPECIALTIES:
        add(f"{spec} Physician", "healthcare", [f"{spec.lower()} doctor", f"{spec.lower()} specialist physician"])
    for spec in _NURSE_SPECIALTIES:
        add(f"{spec} Nurse", "healthcare", [f"{spec.lower()} rn", f"{spec.lower()} registered nurse"])
    for practice in _ATTORNEY_PRACTICES:
        add(f"{practice} Attorney", "legal", [f"{practice.lower()} lawyer", f"{practice.lower()} associate attorney"])
    for canonical, aliases in _ENGINEER_SPECIALTIES:
        add(canonical, "engineering", aliases)
    for domain, function in _MANAGER_DOMAINS:
        add(f"{domain} Manager", function, [f"{domain.lower()} supervisor", f"manager of {domain.lower()}"])
    for domain in _RECRUITER_DOMAINS:
        add(f"{domain} Recruiter", "operations", [f"{domain.lower()} recruitment specialist"])
    for vertical in _AE_VERTICALS:
        add(f"{vertical} Account Executive", "sales", [f"account executive {vertical.lower()}", f"{vertical.lower()} ae"])

    out = sorted(entries.values(), key=lambda e: e["canonical"].lower())
    return out


def main() -> None:
    out = build()
    # Sanity: uniqueness + no alias duplicating its own canonical
    seen: set[str] = set()
    for e in out:
        assert e["canonical"].lower() not in seen, e["canonical"]
        seen.add(e["canonical"].lower())
        assert all(a.lower() != e["canonical"].lower() for a in e["aliases"]), e["canonical"]
    OUT.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    n_aliases = sum(len(e["aliases"]) for e in out)
    print(f"Wrote {len(out)} canonical titles ({n_aliases} aliases) -> {OUT}")


if __name__ == "__main__":
    main()
